### PR TITLE
Split to 3 Maven artifacts, so we have the the environment-specific and common parts isolated

### PR DESCRIPTION
**Pull request by ddekany**
This is mostly because of the "Embed language server instead of starting new JVM" PR that I will soon do on lsp4e-freemarker.

Split freemarker-languageserver to 3 modules: One that has no assumption about the environment it runs in, another which is a CLI application, and another which is an OSGi über-bundle to be used as embedded LSP server in the Eclipse plugin.

Note that I plan to add logging to the "core" module, which abstracts away the logging implementation. (I hope I can use SLF4J.) The actual logging implementation will have to be different under Eclipse and under the CLI application, and so will be provided by the "cli" and "bundle". So that's another reason of the split.

Note that though the "cli" module is now very empty (1 class...), it should later have command line arguments and all that.

### CODE REVIEW

**Comment by angelozerr** [comment]
@ddekany I trust you, I accept your PR

**Comment by angelozerr** [comment]
@ddekany I'm really sorry, I have reverted your PR because I would like to keep for the moment the freemarker-languageserver-all.jar.

I have started to implement a tolerant parser for FM. It's a copy/paste of HTML language service of vscode (writtent in TypeScript). 

Now I must adapt it for FM. Hope you will not angry with this revert.

**Comment by ddekany** [comment]
As of reverting, I'm not angry. (Though I don't really understand the reason, and don't know how logging will work this way... but, we will see.)

As of HTML language service code, how does it relate to the original idea that we re-use BlueSky for the HTML-related parts?

**Comment by angelozerr** [comment]
> Though I don't really understand the reason, and don't know how logging will work this way... but, we will see.

It's because I would liek to keep freemarker-languageserver-all.jar which works too with VSCode. And it's more easy to copy/paste this jar to the lsp4e-freemarker. I mean for the moment! After it should be better to have an OSGi bundle.

> we will see.

Yes we will see. My main goal is to implement the maximum of lsp services.

> As of HTML language service code, how does it relate to the original idea that we re-use BlueSky for the HTML-related parts?

It will change. For the moment I have copied/pasted vscode-html-language-service, but now I must change that to support only FM features (not HTML). It was just the first step. After we will use bluesky to support HTML.

**Pull request merged**
